Repository Vonage/vivid-3, pull requests merged in 2021-11, with the labels that each got.

#4 chore(tests): add karma and jasmine support
  config/karma/karma.conf.dev.cjs
  config/karma/karma.conf.prod.cjs
  config/rollup/rollup.config.base.ts
  config/rollup/rollup.config.prod.ts
  config/rollup/rollup.config.spec.ts
  config/typescript/tsconfig.prod.json
  config/typescript/tsconfig.spec.json
  docs/components/badge.md
  karma.conf.cjs
  package-lock.json
  package.json
  scripts/tsconfig.json
  src/components/badge/badge.spec.ts
  tsconfig.base.json
Labels: Type: Enhancement

#12 docs(badge): readme update
  src/components/badge/README.md
Labels: Type: documentation

#32 chore(CI/CD): add test to pull request
  .github/workflows/pull-request.yml
Labels: Type: chore, Type: CI
