Repository Vonage/vivid-3, pull requests merged in 2022-08, with the labels that each got.

#580 fix(docs): update usage examples
  change/@vonage-vivid-9678fe5c-cf66-4c74-b856-58387b972c86.json
  docs/conventions/readme.md
  libs/components/src/lib/breadcrumb/README.md
  libs/components/src/lib/button/README.md
  libs/components/src/lib/dialog/README.md
  libs/components/src/lib/divider/README.md
  libs/components/src/lib/header/README.md
  libs/components/src/lib/tooltip/README.md
Labels: Focus: Documentation

#590 fix(components): align progress ring default size to baseline
  change/@vonage-vivid-dc87d057-5930-41b7-8104-33a96fb46b13.json
  libs/components/src/lib/progress-ring/progress-ring.scss
  libs/components/src/lib/progress-ring/ui.test.ts-snapshots/snapshots-progress-ring-Chrome-Stable-linux.png
  libs/components/src/lib/progress-ring/ui.test.ts-snapshots/snapshots-progress-ring-Desktop-Firefox-linux.png
  libs/components/src/lib/progress-ring/ui.test.ts-snapshots/snapshots-progress-ring-Desktop-Safari-linux.png
Labels: Type: Fix

#601 fix(docs): remove permanent from dark-mode-toggle
  apps/docs/_layouts/base.njk
Labels: Type: Fix

#599 docs(components): update readme
  README.md
  apps/docs/.eleventy.js
  apps/docs/_layouts/base.njk
  apps/docs/assets/styles/main.css
  assets/images/vivid-cover-wide.avif
  assets/images/vivid-logo.svg
  change/@vonage-vivid-0d32de44-a0c5-4b02-9f01-f94dfb7e8180.json
  libs/components/README.md
  libs/components/package.json
Labels: Focus: Documentation

#607 refactor(components): rename sidenav to nav
  apps/docs/_data/components.json
  apps/docs/_includes/navigation.njk
  apps/docs/_layouts/base.njk
  apps/docs/assets/styles/main.css
  change/@vonage-vivid-b008e95f-6850-49d3-ba8f-6585b9a4a678.json
  libs/components/CHANGELOG.json
  libs/components/CHANGELOG.md
  libs/components/package.json
  libs/components/src/lib/components.ts
  libs/components/src/lib/nav-disclosure/README.md
  libs/components/src/lib/nav-disclosure/index.ts
  libs/components/src/lib/nav-disclosure/nav-disclosure.scss
  libs/components/src/lib/nav-disclosure/nav-disclosure.spec.ts
  libs/components/src/lib/nav-disclosure/nav-disclosure.template.ts
  libs/components/src/lib/nav-disclosure/nav-disclosure.ts
  libs/components/src/lib/nav-disclosure/ui.test.ts
  libs/components/src/lib/nav-disclosure/ui.test.ts-snapshots/snapshots-nav-disclosure-Chrome-Stable-linux.png
  libs/components/src/lib/nav-disclosure/ui.test.ts-snapshots/snapshots-nav-disclosure-Desktop-Firefox-linux.png
  libs/components/src/lib/nav-disclosure/ui.test.ts-snapshots/snapshots-nav-disclosure-Desktop-Safari-linux.png
  libs/components/src/lib/nav-item/README.md
  libs/components/src/lib/nav-item/index.ts
  libs/components/src/lib/nav-item/nav-item.scss
  libs/components/src/lib/nav-item/nav-item.spec.ts
  libs/components/src/lib/nav-item/nav-item.template.ts
  libs/components/src/lib/nav-item/nav-item.ts
  libs/components/src/lib/nav-item/ui.test.ts
  libs/components/src/lib/nav-item/ui.test.ts-snapshots/snapshots-nav-item-Chrome-Stable-linux.png
  libs/components/src/lib/nav-item/ui.test.ts-snapshots/snapshots-nav-item-Desktop-Firefox-linux.png
  libs/components/src/lib/nav-item/ui.test.ts-snapshots/snapshots-nav-item-Desktop-Safari-linux.png
  libs/components/src/lib/nav/README.md
  libs/components/src/lib/nav/index.ts
  libs/components/src/lib/nav/nav.spec.ts
  libs/components/src/lib/nav/nav.template.ts
  libs/components/src/lib/nav/nav.ts
  libs/components/src/lib/nav/ui.test.ts
  libs/components/src/lib/nav/ui.test.ts-snapshots/snapshots-nav-Chrome-Stable-linux.png
  libs/components/src/lib/nav/ui.test.ts-snapshots/snapshots-nav-Desktop-Firefox-linux.png
  libs/components/src/lib/nav/ui.test.ts-snapshots/snapshots-nav-Desktop-Safari-linux.png
  libs/components/src/lib/sidenav-disclosure/README.md
  libs/components/src/lib/sidenav-disclosure/index.ts
  libs/components/src/lib/sidenav-item/README.md
  libs/components/src/lib/sidenav-item/index.ts
  libs/components/src/lib/sidenav/README.md
  libs/components/src/lib/sidenav/index.ts
Labels: Focus: Interface

#604 chore(docs): consider bottom safe area for aside
  apps/docs/_layouts/base.njk
  apps/docs/assets/scripts/main.js
  apps/docs/assets/scripts/scroll-handler.js
  apps/docs/assets/styles/main.css
  apps/docs/pages/component-pages.njk
  apps/docs/pages/designs.njk
Labels: Focus: Documentation

#596 chore(docs): update docs with the CDN links
  change/@vonage-vivid-6d575bec-d8a6-4666-8953-c511baf6b51c.json
  libs/components/README.md
Labels: Focus: Documentation

#507 feat(styles): typography css support
  .github/workflows/_accessibility-validation.yml
  apps/docs/.eleventy.js
  apps/docs/_layouts/base.njk
  apps/docs/assets/styles/main.css
  apps/docs/index.njk
  apps/docs/transformers/wrap-text-elements/index.js
  change/@vonage-vivid-945371a4-98ce-41b7-84d7-5672b0fc1635.json
  libs/components/README.md
  libs/styles/project.json
  libs/styles/src/index.ts
  libs/styles/src/lib/design-tokens.spec.ts
  libs/styles/src/lib/design-tokens.ts
  libs/styles/src/lib/typography/desktop.scss
Labels: Focus: Interface

#623 docs(design-tokens): add new readme
  apps/docs/_data/designs.json
  docs/design/design-tokens.md
Labels: Focus: Documentation

#627 fix(tooltip): readme center
  change/@vonage-vivid-442263ac-29bc-49d4-8b2d-c2c2ddb9616e.json
  libs/components/src/lib/tooltip/README.md
Labels: Focus: Documentation, Type: Fix
