Repository Vonage/vivid-3, pull requests merged in 2022-02, with the labels that each got.

#170 fix(docs): change size from medium to base
  libs/components/src/lib/badge/README.md
  libs/components/src/lib/button/README.md
Labels: Type: documentation, Type: fix

#168 feat(icon): connotation and docs
  libs/components/src/lib/icon/README.md
  libs/components/src/lib/icon/icon.old.tsv
  libs/components/src/lib/icon/icon.scss
  libs/components/src/lib/icon/icon.ts
Labels: Type: fix, Type: Feature

#179 docs(tokens): add color docs
  apps/docs/_data/designs.json
  apps/docs/_includes/navigation.njk
  apps/docs/components/designs.njk
  docs/design/color.md
Labels: Type: documentation, Type: Design 🎨

#184 docs(ui-test): add documentation
  docs/ui-tests/readme.md
Labels: Type: documentation

#182 test(layout): add test coverage
  libs/components/src/lib/layout/README.md
  libs/components/src/lib/layout/layout.spec.ts
  libs/components/src/lib/layout/layout.ts
  libs/components/src/lib/layout/ui.test.ts
  libs/components/src/lib/layout/ui.test.ts-snapshots/snapshots-layout-Chrome-Stable-linux.png
  libs/components/src/lib/layout/ui.test.ts-snapshots/snapshots-layout-Desktop-Firefox-linux.png
  libs/components/src/lib/layout/ui.test.ts-snapshots/snapshots-layout-Desktop-Safari-linux.png
Labels: Type: test, Type: Component 🛠

#198 chore(workspace): dependencies updates
  package-lock.json
  package.json
Labels: dependencies
