Repository Vonage/vivid-3, pull requests merged in 2022-12, with the labels that each got.

#876 perf(components): badge support overflow clipping
  change/@vonage-vivid-9a26360e-1270-491d-a469-ebe97806a2cc.json
  libs/components/src/lib/badge/badge.scss
  libs/components/src/lib/badge/badge.template.ts
  libs/components/src/lib/badge/ui.test.ts
  libs/components/src/lib/badge/ui.test.ts-snapshots/snapshots-badge-Desktop-Chromium-linux.png
  libs/components/src/lib/badge/ui.test.ts-snapshots/snapshots-badge-Desktop-Firefox-linux.png
  libs/components/src/lib/badge/ui.test.ts-snapshots/snapshots-badge-Desktop-Safari-linux.png
Labels: Enhancement, Focus: UI

#883 perf(components): fix button non-responsive display flow
  change/@vonage-vivid-efaece44-ce53-4406-baa3-96a3b00ea7ac.json
  libs/components/src/lib/button/button.scss
Labels: Enhancement, Focus: UI

#873 perf(docs): remove redundant module loading
  apps/docs/pages/component-pages.njk
Labels: Maintenance, Focus: Performance ⏱

#887 fix(dark-mode-toggle): option module import
  apps/docs/_layouts/base.njk
Labels: Type: Fix

#881 feat(doc): a more interactive `--vvd-size-density` example
  apps/docs/_data/designs.json
  apps/docs/assets/scripts/main.js
  apps/docs/transformers/code-block-demo/index.js
  docs/design/design-tokens.md
Labels: Focus: Documentation

#903 feat(popup): anchor can recieve HTMLElement
  change/@vonage-vivid-597cb433-9563-42bc-b3d8-5b6014158f27.json
  libs/components/src/lib/popup/popup.spec.ts
  libs/components/src/lib/popup/popup.ts
Labels: Type: Feature

#862 fix(components): remove hardcoded tags
  change/@vonage-vivid-329e2718-1b3d-45d9-8b6b-33eecb254eaa.json
  libs/components/src/lib/accordion-item/accordion-item.scss
  libs/components/src/lib/accordion-item/accordion-item.template.ts
  libs/components/src/lib/accordion/accordion.scss
  libs/components/src/lib/action-group/action-group.scss
  libs/components/src/lib/avatar/avatar.template.ts
  libs/components/src/lib/banner/banner.template.ts
  libs/components/src/lib/breadcrumb-item/breadcrumb-item.scss
  libs/components/src/lib/breadcrumb-item/breadcrumb-item.template.ts
  libs/components/src/lib/card/card.template.ts
  libs/components/src/lib/dialog/dialog.template.ts
  libs/components/src/lib/nav-disclosure/nav-disclosure.template.ts
  libs/components/src/lib/note/note.template.ts
  libs/components/src/lib/tooltip/tooltip.template.ts
  libs/components/src/shared/patterns/affix.ts
Labels: Type: Refactor :recycle:, Focus: Interface

#907 feat(popup): add absolute strategy
  change/@vonage-vivid-8865978f-8468-4691-a216-12a13c91a92f.json
  libs/components/src/lib/popup/partials/variables.scss
  libs/components/src/lib/popup/popup.scss
  libs/components/src/lib/popup/popup.spec.ts
  libs/components/src/lib/popup/popup.template.ts
  libs/components/src/lib/popup/popup.ts
  libs/components/src/lib/popup/ui.test.ts-snapshots/snapshots-popup-Desktop-Chromium-linux.png
  libs/components/src/lib/popup/ui.test.ts-snapshots/snapshots-popup-Desktop-Firefox-linux.png
  libs/components/src/lib/popup/ui.test.ts-snapshots/snapshots-popup-Desktop-Safari-linux.png
Labels: Type: Feature

#913 fix(calendar): test
  change/@vonage-vivid-5dc8e744-b2cf-46c7-9197-effce0b9e5fb.json
  libs/components/src/lib/calendar/calendar.spec.ts
Labels: Type: Fix

#912 fix(dark-mode): remove unnecessary theme loaders
  apps/docs/_layouts/base.njk
  apps/docs/assets/scripts/theme-handler.js
Labels: Type: Fix

#110 style(code): adopt tsdoc
  change/@vonage-vivid-72f8109d-7ff3-47d1-a6ad-92be7741d088.json
  libs/components/.eslintrc.json
  package-lock.json
  package.json
  tsdoc.json
Labels: Question, Type: Style :star:

#765 feat(popup): add light dismiss support
  change/@vonage-vivid-f46d0b45-7604-483f-8bcb-afe5748b8fd1.json
  libs/components/src/lib/popup/README.md
  libs/components/src/lib/popup/definition.ts
  libs/components/src/lib/popup/popup.spec.ts
  libs/components/src/lib/popup/popup.template.ts
  libs/components/src/lib/popup/popup.ts
  package-lock.json
  package.json
  patches/@oddbird+popover-polyfill+0.0.3.patch
Labels: Enhancement, Type: Feature

#923 fix(listbox): inline size
  change/@vonage-vivid-a87208a5-7106-42b1-9984-0f0858349d16.json
  libs/components/src/lib/listbox/listbox.scss
  libs/components/src/lib/listbox/ui.test.ts
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Chromium-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Firefox-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Safari-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Chromium-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Firefox-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Safari-linux.png
  libs/components/src/lib/option/ui.test.ts
  libs/components/src/lib/option/ui.test.ts-snapshots/snapshots-option-Desktop-Chromium-linux.png
  libs/components/src/lib/option/ui.test.ts-snapshots/snapshots-option-Desktop-Firefox-linux.png
  libs/components/src/lib/option/ui.test.ts-snapshots/snapshots-option-Desktop-Safari-linux.png
Labels: Type: Fix

#927 fix(docs): change to default slot
  change/@vonage-vivid-40ae6409-558b-4b1c-a5dd-345d63d351f9.json
  libs/components/src/lib/listbox/README.md
  libs/components/src/lib/nav/README.md
  libs/components/src/lib/note/README.md
Labels: Focus: Documentation, Type: Fix

#917 chore(components): style listbox `disabled` inherits into option role
  change/@vonage-vivid-a6c794be-d317-4843-8270-a080307e04b5.json
  libs/components/src/lib/listbox/listbox.scss
  libs/components/src/lib/listbox/listbox.spec.ts
  libs/components/src/lib/listbox/listbox.ts
  libs/components/src/lib/listbox/partials/_variables.scss
  libs/components/src/lib/option/option.scss
Labels: Focus: UI

#782 fix(components): harden density customization
  change/@vonage-vivid-f39b91e8-2f54-4e7d-a15c-eff3ae6f3555.json
  libs/components/src/lib/badge/badge.scss
  libs/components/src/lib/banner/banner.scss
  libs/components/src/lib/button/button.scss
  libs/components/src/lib/button/partials/_mixins.scss
  libs/components/src/lib/checkbox/checkbox.scss
  libs/components/src/lib/checkbox/checkbox.template.ts
  libs/components/src/lib/fab/fab.scss
  libs/components/src/lib/fab/ui.test.ts-snapshots/snapshots-fab-Desktop-Chromium-linux.png
  libs/components/src/lib/fab/ui.test.ts-snapshots/snapshots-fab-Desktop-Firefox-linux.png
  libs/components/src/lib/fab/ui.test.ts-snapshots/snapshots-fab-Desktop-Safari-linux.png
  libs/components/src/lib/layout/partials/_variables.scss
  libs/components/src/lib/menu-item/menu-item.scss
  libs/components/src/lib/note/note.scss
  libs/components/src/lib/radio/radio.scss
  libs/components/src/lib/text-field/partials/_variables.scss
  libs/components/src/lib/text-field/text-field.scss
  libs/components/src/lib/text-field/ui.test.ts-snapshots/snapshots-text-field-Desktop-Chromium-linux.png
  libs/components/src/lib/text-field/ui.test.ts-snapshots/snapshots-text-field-Desktop-Firefox-linux.png
  libs/components/src/lib/text-field/ui.test.ts-snapshots/snapshots-text-field-Desktop-Safari-linux.png
Labels: Enhancement, work-in-progress, Focus: UI
