Repository Vonage/vivid-3, pull requests merged in 2022-07, with the labels that each got.

#506 refactor(accordion-item): update docs and icon
  change/@vonage-vivid-1b3099e6-865c-4864-bc6b-b0b0aaab8e56.json
  libs/components/src/lib/accordion-item/README.md
  libs/components/src/lib/accordion-item/accordion-item.scss
  libs/components/src/lib/accordion-item/accordion-item.spec.ts
  libs/components/src/lib/accordion-item/accordion-item.template.ts
  libs/components/src/lib/accordion-item/ui.test.ts-snapshots/snapshots-accordion-item-Chrome-Stable-linux.png
  libs/components/src/lib/accordion-item/ui.test.ts-snapshots/snapshots-accordion-item-Desktop-Firefox-linux.png
  libs/components/src/lib/accordion-item/ui.test.ts-snapshots/snapshots-accordion-item-Desktop-Safari-linux.png
  libs/components/src/lib/accordion/README.md
  libs/components/src/lib/accordion/accordion.scss
  libs/components/src/lib/accordion/accordion.template.ts
  libs/components/src/lib/accordion/ui.test.ts-snapshots/snapshots-accordion-Chrome-Stable-linux.png
  libs/components/src/lib/accordion/ui.test.ts-snapshots/snapshots-accordion-Desktop-Firefox-linux.png
  libs/components/src/lib/accordion/ui.test.ts-snapshots/snapshots-accordion-Desktop-Safari-linux.png
  libs/components/src/lib/sidenav-item/README.md
Labels: Focus: Documentation, Epic: Accordion

#502 refactor(components): side-drawer & header example affected API changes
  apps/docs/_data/components.json
  apps/docs/_includes/navigation.njk
  apps/docs/_layouts/base.njk
  apps/docs/assets/images/moon.svg
  apps/docs/assets/images/sun.png
  apps/docs/assets/images/sun.svg
  apps/docs/assets/images/vvd-logo-full.svg
  apps/docs/assets/scripts/main.js
  apps/docs/assets/styles/main.css
  change/@vonage-vivid-7e3b6f07-bf5f-4d9e-91d6-58eb0aa180c1.json
  libs/components/src/lib/elevation/elevation.scss
  libs/components/src/lib/elevation/elevation.template.ts
  libs/components/src/lib/elevation/elevation.ts
  libs/components/src/lib/header/README.md
  libs/components/src/lib/header/header.scss
  libs/components/src/lib/header/header.spec.ts
  libs/components/src/lib/header/header.template.ts
  libs/components/src/lib/header/header.ts
  libs/components/src/lib/header/index.ts
  libs/components/src/lib/header/partials/_variables.scss
  libs/components/src/lib/header/partials/variables.scss
  libs/components/src/lib/header/ui.test.ts
  libs/components/src/lib/header/ui.test.ts-snapshots/snapshots-header-Chrome-Stable-linux.png
  libs/components/src/lib/header/ui.test.ts-snapshots/snapshots-header-Desktop-Firefox-linux.png
  libs/components/src/lib/header/ui.test.ts-snapshots/snapshots-header-Desktop-Safari-linux.png
  libs/components/src/lib/layout/ui.test.ts-snapshots/snapshots-layout-Desktop-Safari-linux.png
  libs/components/src/lib/side-drawer/README.md
  libs/components/src/lib/side-drawer/partials/_variables.scss
  libs/components/src/lib/side-drawer/partials/variables.scss
  libs/components/src/lib/side-drawer/side-drawer.scss
  libs/components/src/lib/side-drawer/side-drawer.spec.ts
  libs/components/src/lib/side-drawer/side-drawer.template.ts
  libs/components/src/lib/side-drawer/side-drawer.ts
  libs/components/src/lib/side-drawer/ui.test.ts
  libs/components/src/lib/side-drawer/ui.test.ts-snapshots/snapshots-side-drawer-Chrome-Stable-linux.png
  libs/components/src/lib/side-drawer/ui.test.ts-snapshots/snapshots-side-drawer-Desktop-Firefox-linux.png
  libs/components/src/lib/side-drawer/ui.test.ts-snapshots/snapshots-side-drawer-Desktop-Safari-linux.png
  libs/components/src/lib/side-drawer/ui.test.ts-snapshots/snapshots-side-drawer-modal-Chrome-Stable-linux.png
  libs/components/src/lib/side-drawer/ui.test.ts-snapshots/snapshots-side-drawer-modal-Desktop-Firefox-linux.png
  libs/components/src/lib/side-drawer/ui.test.ts-snapshots/snapshots-side-drawer-modal-Desktop-Safari-linux.png
Labels: Focus: Interface

#495 refactor(sidenav): new component
  apps/docs/_data/components.json
  apps/docs/_includes/navigation.njk
  apps/docs/_layouts/base.njk
  apps/docs/assets/styles/main.css
  change/@vonage-vivid-eb2e0c3d-1467-441c-a29f-6d551407e326.json
  libs/components/package.json
  libs/components/src/lib/components.ts
  libs/components/src/lib/sidenav/README.md
  libs/components/src/lib/sidenav/index.ts
  libs/components/src/lib/sidenav/sidenav.spec.ts
  libs/components/src/lib/sidenav/sidenav.template.ts
  libs/components/src/lib/sidenav/sidenav.ts
  libs/components/src/lib/sidenav/ui.test.ts
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Chrome-Stable-linux.png
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Desktop-Firefox-linux.png
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Desktop-Safari-linux.png
Labels: Epic: Sidenav

#527 fix(components): side drawer blocking elements
  apps/docs/assets/styles/main.css
  change/@vonage-vivid-11fc3288-4c62-42d5-865f-cc25226210b3.json
  libs/components/src/lib/header/header.scss
  libs/components/src/lib/side-drawer/side-drawer.scss
  libs/components/src/lib/side-drawer/side-drawer.template.ts
  libs/components/src/lib/side-drawer/side-drawer.ts
  package-lock.json
  package.json
Labels: Type: Fix

#533 fix(tooltip): accessibility
  change/@vonage-vivid-a7871cee-d381-4f5c-843c-6153262e9281.json
  libs/components/src/lib/popup/README.md
  libs/components/src/lib/popup/popup.spec.ts
  libs/components/src/lib/popup/popup.ts
  libs/components/src/lib/tooltip/README.md
  libs/components/src/lib/tooltip/tooltip.template.ts
Labels: Epic: Tooltip

#503 refactor(sidenav-disclosure): add new component
  apps/docs/_data/components.json
  change/@vonage-vivid-386321a4-cf7b-4d0c-970f-460275001159.json
  libs/components/package.json
  libs/components/src/lib/sidenav-disclosure/README.md
  libs/components/src/lib/sidenav-disclosure/index.ts
  libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
  libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.spec.ts
  libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.template.ts
  libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.ts
  libs/components/src/lib/sidenav-disclosure/ui.test.ts
  libs/components/src/lib/sidenav-disclosure/ui.test.ts-snapshots/snapshots-sidenav-disclosure-Chrome-Stable-linux.png
  libs/components/src/lib/sidenav-disclosure/ui.test.ts-snapshots/snapshots-sidenav-disclosure-Desktop-Firefox-linux.png
  libs/components/src/lib/sidenav-disclosure/ui.test.ts-snapshots/snapshots-sidenav-disclosure-Desktop-Safari-linux.png
  libs/components/src/lib/sidenav-item/README.md
  libs/components/src/lib/sidenav-item/ui.test.ts-snapshots/snapshots-sidenav-item-Chrome-Stable-linux.png
  libs/components/src/lib/sidenav-item/ui.test.ts-snapshots/snapshots-sidenav-item-Desktop-Firefox-linux.png
  libs/components/src/lib/sidenav-item/ui.test.ts-snapshots/snapshots-sidenav-item-Desktop-Safari-linux.png
  libs/components/src/lib/sidenav/README.md
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Chrome-Stable-linux.png
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Desktop-Firefox-linux.png
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Desktop-Safari-linux.png
Labels: Focus: Component 🛠, Epic: Sidenav

#141 docs(button): example toggle button practice
  change/@vonage-vivid-5e41429d-47b0-48e5-afb9-10262b96eb81.json
  libs/components/src/lib/button/README.md
  libs/components/src/lib/button/ui.test.ts-snapshots/snapshots-button-Chrome-Stable-linux.png
  libs/components/src/lib/button/ui.test.ts-snapshots/snapshots-button-Desktop-Firefox-linux.png
  libs/components/src/lib/button/ui.test.ts-snapshots/snapshots-button-Desktop-Safari-linux.png
Labels: Focus: Documentation

#550 fix(mobile): add user-select to components
  change/@vonage-vivid-4e6cf30c-6650-4237-9222-fbb96e601a18.json
  libs/components/src/lib/accordion-item/accordion-item.scss
  libs/components/src/lib/button/button.scss
  libs/components/src/lib/fab/fab.scss
  libs/components/src/lib/sidenav-disclosure/sidenav-disclosure.scss
Labels: Type: Fix

#553 fix(header): docs and slots
  apps/docs/_layouts/base.njk
  change/@vonage-vivid-e4232447-4b45-4553-8f02-2a731e02bec4.json
  libs/components/src/lib/header/README.md
  libs/components/src/lib/header/header.template.ts
  libs/components/src/lib/header/ui.test.ts
Labels: Focus: Documentation, Type: Fix

#475 chore(docs): note on icon-only a11y pitfall
  change/@vonage-vivid-5fdc372c-1ccb-4aa0-bbd1-899283bb87c8.json
  libs/components/src/lib/button/README.md
  libs/components/src/lib/fab/README.md
  libs/components/src/lib/fab/ui.test.ts-snapshots/snapshots-fab-Chrome-Stable-linux.png
  libs/components/src/lib/fab/ui.test.ts-snapshots/snapshots-fab-Desktop-Firefox-linux.png
  libs/components/src/lib/fab/ui.test.ts-snapshots/snapshots-fab-Desktop-Safari-linux.png
  libs/components/src/lib/sidenav-item/README.md
  libs/components/src/lib/sidenav-item/ui.test.ts-snapshots/snapshots-sidenav-item-Chrome-Stable-linux.png
  libs/components/src/lib/sidenav-item/ui.test.ts-snapshots/snapshots-sidenav-item-Desktop-Firefox-linux.png
  libs/components/src/lib/sidenav-item/ui.test.ts-snapshots/snapshots-sidenav-item-Desktop-Safari-linux.png
Labels: Focus: Documentation, Focus: A11y ♿️

#554 fix(banner): docs and slots
  change/@vonage-vivid-149300ea-b1b5-4e46-9186-673cf16c6f20.json
  libs/components/src/lib/banner/README.md
  libs/components/src/lib/banner/banner.spec.ts
  libs/components/src/lib/banner/banner.template.ts
  libs/components/src/lib/banner/banner.ts
  libs/components/src/lib/banner/ui.test.ts-snapshots/snapshots-banner-Chrome-Stable-linux.png
  libs/components/src/lib/banner/ui.test.ts-snapshots/snapshots-banner-Desktop-Firefox-linux.png
  libs/components/src/lib/banner/ui.test.ts-snapshots/snapshots-banner-Desktop-Safari-linux.png
Labels: Epic: Banner

#555 fix(dialog): docs and closing event name
  change/@vonage-vivid-46d61f91-5bb8-4066-b00d-d5eba9708735.json
  libs/components/src/lib/dialog/README.md
Labels: Focus: Documentation

#565 chore(docs): add sidenav-disclosure to docs
  apps/docs/_includes/navigation.njk
  apps/docs/_layouts/base.njk
  apps/docs/assets/styles/main.css
Labels: Focus: Documentation

#568 fix(docs): update with the new conventions
  change/@vonage-nx-vivid-91f4ec04-baf4-4665-be39-1c815b0116b4.json
  change/@vonage-vivid-10c91609-cac6-471e-a5a2-c72e3b697eae.json
  libs/components/src/lib/accordion-item/README.md
  libs/components/src/lib/accordion/README.md
  libs/components/src/lib/action-group/README.md
  libs/components/src/lib/badge/README.md
  libs/components/src/lib/banner/README.md
  libs/components/src/lib/breadcrumb-item/README.md
  libs/components/src/lib/breadcrumb/README.md
  libs/components/src/lib/button/README.md
  libs/components/src/lib/calendar/README.md
  libs/components/src/lib/card/README.md
  libs/components/src/lib/dialog/README.md
  libs/components/src/lib/divider/README.md
  libs/components/src/lib/elevation/README.md
  libs/components/src/lib/fab/README.md
  libs/components/src/lib/focus/README.md
  libs/components/src/lib/header/README.md
  libs/components/src/lib/icon/README.md
  libs/components/src/lib/layout/README.md
  libs/components/src/lib/note/README.md
  libs/components/src/lib/progress-ring/README.md
  libs/components/src/lib/progress/README.md
  libs/components/src/lib/side-drawer/README.md
  libs/components/src/lib/sidenav-disclosure/README.md
  libs/components/src/lib/sidenav/README.md
  libs/components/src/lib/text-anchor/README.md
  libs/components/src/lib/text-field/README.md
  libs/components/src/lib/text/README.md
  libs/components/src/lib/tooltip/README.md
  libs/nx-vivid/src/generators/component/files/README.md__tmpl__
Labels: Focus: Documentation

#575 chore(sidenav): add aria-current examples
  change/@vonage-vivid-036f30b5-bf1c-4f02-8930-3898123d5823.json
  libs/components/src/lib/sidenav-item/README.md
  libs/components/src/lib/sidenav/README.md
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Chrome-Stable-linux.png
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Desktop-Firefox-linux.png
  libs/components/src/lib/sidenav/ui.test.ts-snapshots/snapshots-sidenav-Desktop-Safari-linux.png
Labels: Epic: Sidenav
