Repository Vonage/vivid-3, pull requests merged in 2022-03, with the labels that each got.

#229 refactor(themes): auto generated tokens
  change/@vivid-nx-styles-26a4794a-03a2-4957-998f-9b5ee34826f0.json
  libs/styles/src/lib/themes/dark.scss
  libs/styles/src/lib/themes/light.scss
  libs/styles/src/lib/themes/partials/_theme-mixins.scss
  libs/styles/src/lib/themes/partials/_theme-variables.scss
Labels: Type: Design 🎨

#211 refactor(elevation): migrate to fast element
  apps/docs/_data/components.json
  change/@vonage-vivid-e9b24263-24c8-4f6f-b317-d079a316e584.json
  libs/components/src/lib/components.ts
  libs/components/src/lib/elevation/README.md
  libs/components/src/lib/elevation/elevation.scss
  libs/components/src/lib/elevation/elevation.spec.ts
  libs/components/src/lib/elevation/elevation.template.ts
  libs/components/src/lib/elevation/elevation.ts
  libs/components/src/lib/elevation/index.ts
  libs/components/src/lib/elevation/ui.test.ts
  libs/components/src/lib/elevation/ui.test.ts-snapshots/snapshots-elevation-Chrome-Stable-linux.png
  libs/components/src/lib/elevation/ui.test.ts-snapshots/snapshots-elevation-Desktop-Firefox-linux.png
  libs/components/src/lib/elevation/ui.test.ts-snapshots/snapshots-elevation-Desktop-Safari-linux.png
  libs/shared/src/lib/test-utils/index.ts
Labels: Type: Component 🛠

#234 refactor(docs): add components roadmap
  README.md
  docs/components.md
Labels: Type: documentation

#227 chore(docs): convert demo divs to iframes
  apps/docs/.eleventy.js
  apps/docs/transformers/code-block-demo.js
  package-lock.json
  package.json
Labels: Type: documentation

#268 refactor(elevation): no default dom mutation
  change/@vonage-vivid-35b7727d-c585-4a11-83eb-3935251ac8ce.json
  libs/components/src/lib/elevation/README.md
  libs/components/src/lib/elevation/elevation.scss
  libs/components/src/lib/elevation/elevation.spec.ts
  libs/components/src/lib/elevation/elevation.ts
  libs/components/src/lib/elevation/partials/_elevation.mixin.scss
  libs/components/src/lib/elevation/ui.test.ts-snapshots/snapshots-elevation-Chrome-Stable-linux.png
  libs/components/src/lib/elevation/ui.test.ts-snapshots/snapshots-elevation-Desktop-Firefox-linux.png
  libs/components/src/lib/elevation/ui.test.ts-snapshots/snapshots-elevation-Desktop-Safari-linux.png
  libs/shared/src/lib/sass/mixins/utils/_spread-list-selectors.scss
  libs/shared/src/lib/sass/mixins/utils/index.scss
Labels: type: style :star:

#194 test(components): lint rule prevent dom-mutating-attribute
  change/@vonage-vivid-0ec43289-1457-44a5-98fc-e7aed546e0e4.json
  libs/components/.eslintrc.json
  libs/components/src/lib/badge/badge.ts
  libs/components/src/lib/breadcrumb-item/breadcrumb-item.ts
  libs/components/src/lib/breadcrumb/breadcrumb.spec.ts
  libs/components/src/lib/breadcrumb/ui.test.ts
  libs/components/src/lib/button/button.ts
  libs/components/src/lib/elevation/elevation.ts
  libs/components/src/lib/sidenav-item/sidenav-item.ts
  libs/components/src/lib/text-anchor/text-anchor.ts
  nx.json
  package-lock.json
  package.json
  tools/eslint-rules/index.ts
  tools/eslint-rules/jest.config.js
  tools/eslint-rules/project.json
  tools/eslint-rules/rules/no-attribute-default-value.spec.ts
  tools/eslint-rules/rules/no-attribute-default-value.ts
  tools/eslint-rules/tsconfig.json
  tools/eslint-rules/tsconfig.lint.json
  tools/eslint-rules/tsconfig.spec.json
  workspace.json
Labels: Type: Maintenance, Type: test, Type: CI

#276 fix(docs): color
  docs/design/color.md
Labels: Type: documentation
