Repository Vonage/vivid-3, pull requests merged in 2022-11, with the labels that each got.

#794 fix(card): remove expect import
  change/@vonage-vivid-3a5bbfc4-f0d2-43ae-8cb3-1d66cd716ffe.json
  libs/components/src/lib/card/card.spec.ts
Labels: Type: Fix, Type: Test

#635 feat(listbox): add new component
  apps/docs/_data/components.json
  change/@vonage-vivid-f063d3ce-a4c3-44c1-99fd-3c2c85fc375e.json
  libs/components/package.json
  libs/components/src/lib/components.ts
  libs/components/src/lib/listbox-option/README.md
  libs/components/src/lib/listbox-option/listbox-option.scss
  libs/components/src/lib/listbox-option/ui.test.ts
  libs/components/src/lib/listbox-option/ui.test.ts-snapshots/snapshots-listbox-option-Desktop-Chromium-linux.png
  libs/components/src/lib/listbox-option/ui.test.ts-snapshots/snapshots-listbox-option-Desktop-Firefox-linux.png
  libs/components/src/lib/listbox-option/ui.test.ts-snapshots/snapshots-listbox-option-Desktop-Safari-linux.png
  libs/components/src/lib/listbox/README.md
  libs/components/src/lib/listbox/index.ts
  libs/components/src/lib/listbox/listbox.scss
  libs/components/src/lib/listbox/listbox.spec.ts
  libs/components/src/lib/listbox/listbox.template.ts
  libs/components/src/lib/listbox/listbox.ts
  libs/components/src/lib/listbox/ui.test.ts
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Chromium-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Firefox-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Safari-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Chromium-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Firefox-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Safari-linux.png
  libs/components/src/lib/note/ui.test.ts-snapshots/snapshots-note-Desktop-Chromium-linux.png
  libs/components/src/lib/note/ui.test.ts-snapshots/snapshots-note-Desktop-Firefox-linux.png
  libs/components/src/lib/note/ui.test.ts-snapshots/snapshots-note-Desktop-Safari-linux.png
  libs/shared/src/lib/sass/mixins/appearance/_variables.scss
  libs/shared/src/lib/sass/mixins/connotation/_variables.scss
Labels: Enhancement, Type: Feature

#799 feat(docs): change icon when copy from clipboard
  apps/docs/assets/scripts/main.js
Labels: Focus: Documentation, Enhancement

#800 fix(docs): horizontal scroll in mobile main page
  README.md
  apps/docs/assets/styles/main.css
  change/@vonage-vivid-81d59a1e-60f0-4ef1-acbc-eb5ad8638c38.json
Labels: Focus: Documentation, Type: Fix

#813 feat(docs): add scroll localStorage to side drawer
  apps/docs/assets/scripts/scroll-handler.js
Labels: Focus: Documentation, Type: Feature

#776 docs(components): refine progress ring code snippets
  change/@vonage-vivid-10e5a260-5f23-473c-95c8-9f405c4e7c13.json
  libs/components/src/lib/progress-ring/README.md
Labels: Focus: Documentation

#834 refactor(components): calendar css style to enable dark-theme background
  change/@vonage-vivid-8b23e155-dfb1-449b-84a5-e25856b5f347.json
  libs/components/src/lib/calendar/calendar.scss
Labels: Type: Fix

#850 refactor(components): style gutters and gaps in child items
  change/@vonage-vivid-593ef030-995b-4ffd-9df0-907185a04050.json
  libs/components/src/lib/listbox-option/listbox-option.scss
  libs/components/src/lib/listbox-option/ui.test.ts-snapshots/snapshots-listbox-option-Desktop-Chromium-linux.png
  libs/components/src/lib/listbox-option/ui.test.ts-snapshots/snapshots-listbox-option-Desktop-Firefox-linux.png
  libs/components/src/lib/listbox-option/ui.test.ts-snapshots/snapshots-listbox-option-Desktop-Safari-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Chromium-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Firefox-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-Desktop-Safari-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Chromium-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Firefox-linux.png
  libs/components/src/lib/listbox/ui.test.ts-snapshots/snapshots-listbox-focus-Desktop-Safari-linux.png
  libs/components/src/lib/menu-item/menu-item.scss
  libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Chromium-linux.png
  libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Firefox-linux.png
  libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Safari-linux.png
  libs/components/src/lib/menu/ui.test.ts-snapshots/snapshots-menu-Desktop-Chromium-linux.png
  libs/components/src/lib/menu/ui.test.ts-snapshots/snapshots-menu-Desktop-Firefox-linux.png
  libs/components/src/lib/menu/ui.test.ts-snapshots/snapshots-menu-Desktop-Safari-linux.png
  libs/components/src/lib/nav-disclosure/nav-disclosure.scss
  libs/components/src/lib/nav-disclosure/ui.test.ts-snapshots/snapshots-nav-disclosure-Desktop-Chromium-linux.png
  libs/components/src/lib/nav-disclosure/ui.test.ts-snapshots/snapshots-nav-disclosure-Desktop-Firefox-linux.png
  libs/components/src/lib/nav-disclosure/ui.test.ts-snapshots/snapshots-nav-disclosure-Desktop-Safari-linux.png
  libs/components/src/lib/nav-item/nav-item.scss
  libs/components/src/lib/nav-item/ui.test.ts-snapshots/snapshots-nav-item-Desktop-Chromium-linux.png
  libs/components/src/lib/nav-item/ui.test.ts-snapshots/snapshots-nav-item-Desktop-Firefox-linux.png
  libs/components/src/lib/nav-item/ui.test.ts-snapshots/snapshots-nav-item-Desktop-Safari-linux.png
  libs/components/src/lib/nav/ui.test.ts-snapshots/snapshots-nav-Desktop-Chromium-linux.png
  libs/components/src/lib/nav/ui.test.ts-snapshots/snapshots-nav-Desktop-Firefox-linux.png
  libs/components/src/lib/nav/ui.test.ts-snapshots/snapshots-nav-Desktop-Safari-linux.png
Labels: Focus: Vivid Parity

#791 feat(docs): add doc for public CSS references
  apps/docs/_data/designs.json
  docs/design/design-tokens.md
Labels: Focus: Documentation

#829 refactor(tooltip): disable manual handling of open state
  apps/docs/_data/components.json
  change/@vonage-vivid-f5eef4cf-9d07-4480-a4e6-bbf91bec130f.json
  libs/components/src/lib/popup/popup.ts
  libs/components/src/lib/tooltip/README.md
  libs/components/src/lib/tooltip/tooltip.scss
  libs/components/src/lib/tooltip/tooltip.spec.ts
  libs/components/src/lib/tooltip/tooltip.template.ts
  libs/components/src/lib/tooltip/tooltip.ts
  libs/components/src/lib/tooltip/ui.test.ts-snapshots/snapshots-tooltip-Desktop-Chromium-linux.png
  libs/components/src/lib/tooltip/ui.test.ts-snapshots/snapshots-tooltip-Desktop-Firefox-linux.png
  libs/components/src/lib/tooltip/ui.test.ts-snapshots/snapshots-tooltip-Desktop-Safari-linux.png
Labels: Type: Refactor :recycle:

#868 fix(menu-item): lint
  change/@vonage-vivid-f3113520-c6ca-487b-a569-91c3c99f7464.json
  libs/components/src/lib/menu-item/menu-item.scss
Labels: Type: Fix, Type: Style :star:
