Repository Vonage/vivid-3, pull requests merged in 2023-03, with the labels that each got.

#1045 chore(option): add value example
  libs/components/src/lib/checkbox/README.md
  libs/components/src/lib/checkbox/checkbox.spec.ts
  libs/components/src/lib/checkbox/ui.test.ts-snapshots/snapshots-checkbox-Desktop-Chromium-linux.png
  libs/components/src/lib/checkbox/ui.test.ts-snapshots/snapshots-checkbox-Desktop-Firefox-linux.png
  libs/components/src/lib/checkbox/ui.test.ts-snapshots/snapshots-checkbox-Desktop-Safari-linux.png
  libs/components/src/lib/option/README.md
  libs/components/src/lib/option/option.spec.ts
  libs/components/src/lib/option/ui.test.ts-snapshots/snapshots-option-Desktop-Chromium-linux.png
  libs/components/src/lib/option/ui.test.ts-snapshots/snapshots-option-Desktop-Firefox-linux.png
  libs/components/src/lib/option/ui.test.ts-snapshots/snapshots-option-Desktop-Safari-linux.png
  libs/components/src/lib/radio/README.md
  libs/components/src/lib/radio/radio.spec.ts
  libs/components/src/lib/radio/ui.test.ts-snapshots/snapshots-radio-Desktop-Chromium-linux.png
  libs/components/src/lib/radio/ui.test.ts-snapshots/snapshots-radio-Desktop-Firefox-linux.png
  libs/components/src/lib/radio/ui.test.ts-snapshots/snapshots-radio-Desktop-Safari-linux.png
  libs/components/src/lib/slider/README.md
  libs/components/src/lib/switch/README.md
  libs/components/src/lib/switch/ui.test.ts-snapshots/snapshots-switch-Desktop-Chromium-linux.png
  libs/components/src/lib/switch/ui.test.ts-snapshots/snapshots-switch-Desktop-Firefox-linux.png
  libs/components/src/lib/switch/ui.test.ts-snapshots/snapshots-switch-Desktop-Safari-linux.png
Labels: Focus: Documentation

#1076 feat(select): add icon
  libs/components/src/lib/select/README.md
  libs/components/src/lib/select/select.scss
  libs/components/src/lib/select/select.spec.ts
  libs/components/src/lib/select/select.template.ts
  libs/components/src/lib/select/select.ts
  libs/components/src/lib/select/ui.test.ts
  libs/components/src/lib/select/ui.test.ts-snapshots/snapshots-select-Desktop-Chromium-linux.png
  libs/components/src/lib/select/ui.test.ts-snapshots/snapshots-select-Desktop-Firefox-linux.png
  libs/components/src/lib/select/ui.test.ts-snapshots/snapshots-select-Desktop-Safari-linux.png
Labels: work-in-progress

#837 perf(components): action group role as group (VIV-897)
  libs/components/src/lib/action-group/README.md
  libs/components/src/lib/action-group/action-group.spec.ts
  libs/components/src/lib/action-group/action-group.template.ts
  libs/components/src/lib/action-group/action-group.ts
Labels: Focus: A11y 🧑‍🦽
