Repository Vonage/vivid-3, pull requests merged in 2023-02, with the labels that each got.

#902 chore(workspace): update production dependencies
  libs/components/src/lib/combobox/ui.test.ts-snapshots/snapshots-combobox-Desktop-Firefox-linux.png
  package-lock.json
  package.json
Labels: Maintenance

#987 feat(tree): add component
  apps/docs/_data/components.json
  libs/components/src/lib/components.ts
  libs/components/src/lib/tree-item/README.md
  libs/components/src/lib/tree-item/definition.ts
  libs/components/src/lib/tree-item/index.ts
  libs/components/src/lib/tree-item/tree-item.scss
  libs/components/src/lib/tree-item/tree-item.spec.ts
  libs/components/src/lib/tree-item/tree-item.template.ts
  libs/components/src/lib/tree-item/tree-item.ts
  libs/components/src/lib/tree-item/ui.test.ts
  libs/components/src/lib/tree-item/ui.test.ts-snapshots/snapshots-tree-item-Desktop-Chromium-linux.png
  libs/components/src/lib/tree-item/ui.test.ts-snapshots/snapshots-tree-item-Desktop-Firefox-linux.png
  libs/components/src/lib/tree-item/ui.test.ts-snapshots/snapshots-tree-item-Desktop-Safari-linux.png
  libs/components/src/lib/tree-view/README.md
  libs/components/src/lib/tree-view/definition.ts
  libs/components/src/lib/tree-view/index.ts
  libs/components/src/lib/tree-view/tree-view.scss
  libs/components/src/lib/tree-view/tree-view.spec.ts
  libs/components/src/lib/tree-view/tree-view.template.ts
  libs/components/src/lib/tree-view/tree-view.ts
  libs/components/src/lib/tree-view/ui.test.ts
  libs/components/src/lib/tree-view/ui.test.ts-snapshots/snapshots-tree-view-Desktop-Chromium-linux.png
  libs/components/src/lib/tree-view/ui.test.ts-snapshots/snapshots-tree-view-Desktop-Firefox-linux.png
  libs/components/src/lib/tree-view/ui.test.ts-snapshots/snapshots-tree-view-Desktop-Safari-linux.png
Labels: Type: Feature

#1032 fix(docs): scroll uses sessionStorage instead of localStorage
  apps/docs/assets/scripts/scroll-handler.js
Labels: Focus: Documentation, Type: Fix
