Repository Vonage/vivid-3, pull requests merged in 2023-01, with the labels that each got.

#825 feat(components): combobox new component
  apps/docs/_data/components.json
  change/@vonage-vivid-d5251609-36b2-4a14-82ef-f7815f083bdb.json
  libs/components/src/lib/combobox/README.md
  libs/components/src/lib/combobox/combobox.scss
  libs/components/src/lib/combobox/combobox.spec.ts
  libs/components/src/lib/combobox/combobox.template.ts
  libs/components/src/lib/combobox/combobox.ts
  libs/components/src/lib/combobox/definition.ts
  libs/components/src/lib/combobox/index.ts
  libs/components/src/lib/combobox/ui.test.ts
  libs/components/src/lib/combobox/ui.test.ts-snapshots/snapshots-combobox-Desktop-Chromium-linux.png
  libs/components/src/lib/combobox/ui.test.ts-snapshots/snapshots-combobox-Desktop-Firefox-linux.png
  libs/components/src/lib/combobox/ui.test.ts-snapshots/snapshots-combobox-Desktop-Safari-linux.png
  libs/components/src/lib/components.ts
Labels: Type: Feature

#948 docs(icon): add px to icon docs
  change/@vonage-vivid-4fc6aef8-6510-4c0a-b87b-eb696515e417.json
  libs/components/src/lib/icon/README.md
  libs/components/src/lib/icon/ui.test.ts-snapshots/snapshots-icon-Desktop-Chromium-linux.png
  libs/components/src/lib/icon/ui.test.ts-snapshots/snapshots-icon-Desktop-Firefox-linux.png
  libs/components/src/lib/icon/ui.test.ts-snapshots/snapshots-icon-Desktop-Safari-linux.png
Labels: Focus: Documentation

#131 test(audit): lighthouse integration
  .github/workflows/_lighthouse.yml
  .github/workflows/pull-request.yml
  lighthouserc.json
Labels: help wanted, Type: Test

#699 refactor(components): migrate tabs to fast
  apps/docs/_data/components.json
  change/@vonage-vivid-2a348579-786f-4a9f-ad02-1f78b3e05d22.json
  libs/components/src/lib/components.ts
  libs/components/src/lib/tab-panel/definition.ts
  libs/components/src/lib/tab-panel/index.ts
  libs/components/src/lib/tab-panel/tab-panel.spec.ts
  libs/components/src/lib/tab-panel/tab-panel.template.ts
  libs/components/src/lib/tab-panel/tab-panel.ts
  libs/components/src/lib/tab/README.md
  libs/components/src/lib/tab/definition.ts
  libs/components/src/lib/tab/index.ts
  libs/components/src/lib/tab/tab.scss
  libs/components/src/lib/tab/tab.spec.ts
  libs/components/src/lib/tab/tab.template.ts
  libs/components/src/lib/tab/tab.ts
  libs/components/src/lib/tab/ui.test.ts
  libs/components/src/lib/tab/ui.test.ts-snapshots/snapshots-tab-Desktop-Chromium-linux.png
  libs/components/src/lib/tab/ui.test.ts-snapshots/snapshots-tab-Desktop-Firefox-linux.png
  libs/components/src/lib/tab/ui.test.ts-snapshots/snapshots-tab-Desktop-Safari-linux.png
  libs/components/src/lib/tabs/README.md
  libs/components/src/lib/tabs/definition.ts
  libs/components/src/lib/tabs/index.ts
  libs/components/src/lib/tabs/partials/_variables.scss
  libs/components/src/lib/tabs/tabs.scss
  libs/components/src/lib/tabs/tabs.spec.ts
  libs/components/src/lib/tabs/tabs.template.ts
  libs/components/src/lib/tabs/tabs.ts
  libs/components/src/lib/tabs/ui.test.ts
  libs/components/src/lib/tabs/ui.test.ts-snapshots/snapshots-tabs-Desktop-Chromium-linux.png
  libs/components/src/lib/tabs/ui.test.ts-snapshots/snapshots-tabs-Desktop-Firefox-linux.png
  libs/components/src/lib/tabs/ui.test.ts-snapshots/snapshots-tabs-Desktop-Safari-linux.png
Labels: Type: Feature

#849 feat(components): menu item support secondary text
  change/@vonage-vivid-f5342a8c-ad74-47de-a447-5d078ee5dae6.json
  libs/components/src/lib/menu-item/README.md
  libs/components/src/lib/menu-item/menu-item.scss
  libs/components/src/lib/menu-item/menu-item.spec.ts
  libs/components/src/lib/menu-item/menu-item.template.ts
  libs/components/src/lib/menu-item/menu-item.ts
  libs/components/src/lib/menu-item/ui.test.ts
  libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Chromium-linux.png
  libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Firefox-linux.png
  libs/components/src/lib/menu-item/ui.test.ts-snapshots/snapshots-menu-item-Desktop-Safari-linux.png
Labels: Type: Feature, Focus: Vivid Parity, Focus: UI

#959 chore(dark mode): add light dismiss
  apps/docs/_layouts/base.njk
Labels: Type: Chore

#974 fix(mobile): add pointer-events none
  change/@vonage-vivid-76c6ee66-4ebe-4b5e-86c3-cf92b682d7e7.json
  libs/components/src/lib/checkbox/checkbox.scss
  libs/components/src/lib/menu-item/menu-item.scss
  libs/components/src/lib/option/option.scss
  libs/components/src/lib/radio/radio.scss
  libs/components/src/lib/select/select.scss
  libs/components/src/lib/slider/slider.scss
  libs/components/src/lib/switch/switch.scss
  libs/components/src/lib/tab/tab.scss
  libs/components/src/lib/text-area/text-area.scss
Labels: Type: Fix

#975 fix(text-area): add disabled
  change/@vonage-vivid-cd2552c3-de35-4f67-98de-e350d8777d0e.json
  libs/components/src/lib/text-area/text-area.template.ts
Labels: Type: Fix

#979 fix(docs): side drawer color
  docs/design/color-palette.md
Labels: Focus: Documentation, Type: Fix

#990 docs(main): update main README.md
  .github/CONTRIBUTING.md
  README.md
Labels: Focus: Documentation, Type: Fix
